//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ic_ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ebay
    {
        public int row_id { get; set; }
        public string order_id { get; set; }
        public System.DateTime ship_date { get; set; }
        public string order_status { get; set; }
        public string payment_method { get; set; }
        public System.DateTime order_date { get; set; }
        public string order_total { get; set; }
        public string ship_name { get; set; }
        public string ship_address { get; set; }
        public string ship_city { get; set; }
        public string ship_state { get; set; }
        public string ship_zip { get; set; }
        public string carrier { get; set; }
        public string tax { get; set; }
    }
}
