//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ic_ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class magento_stock_log
    {
        public int id { get; set; }
        public string sku { get; set; }
        public System.DateTime time { get; set; }
        public int qty { get; set; }
    }
}
