//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ic_ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class magento_validation_log
    {
        public int row_id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string SKU { get; set; }
        public Nullable<decimal> bin_qty { get; set; }
        public Nullable<decimal> mage_qty { get; set; }
        public string successful { get; set; }
    }
}
