//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ic_ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class pull_log
    {
        public Nullable<System.DateTime> time { get; set; }
        public int record_id { get; set; }
        public string ictag { get; set; }
        public string sku { get; set; }
        public string channel { get; set; }
        public string action { get; set; }
    }
}
