//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ic_ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class retail_report
    {
        public int row_id { get; set; }
        public System.DateTime date_sold { get; set; }
        public string ictag { get; set; }
        public string price_sold { get; set; }
        public string name { get; set; }
        public string receipt { get; set; }
        public string type { get; set; }
    }
}
