//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ic_ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class retail
    {
        public Nullable<System.DateTime> time { get; set; }
        public int asset_tag { get; set; }
        public double price { get; set; }
        public string custom_label { get; set; }
        public string cpu { get; set; }
        public string ram { get; set; }
        public string hdd { get; set; }
        public string model { get; set; }
        public string sold { get; set; }
    }
}
