//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ic_ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipstation_log
    {
        public int row_id { get; set; }
        public Nullable<System.DateTime> shipment_date { get; set; }
        public Nullable<int> order_id { get; set; }
        public string order_num { get; set; }
        public string item_name { get; set; }
        public Nullable<int> item_qty { get; set; }
        public string item_url { get; set; }
        public string custom_field_1 { get; set; }
        public string custom_field_2 { get; set; }
        public string custom_field_3 { get; set; }
        public string status { get; set; }
        public int store_id { get; set; }
        public string sku { get; set; }
    }
}
