//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ic_ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipstation_shipment_log
    {
        public int row_id { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<int> shipment_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string order_number { get; set; }
        public Nullable<System.DateTime> ship_date { get; set; }
        public string item_name { get; set; }
        public string item_sku { get; set; }
        public string image_url { get; set; }
        public Nullable<int> item_qty { get; set; }
    }
}
